import { locales, type AppLocale } from "./config";

/** Built-in packs shipped as JSON under messages/. */
export const FIXED_UI_LOCALES = locales;

export type FixedUiLocale = AppLocale;

/** Extended UI languages generated by Locale Pack Agent (BYOK). */
export const DYNAMIC_UI_LOCALES = [
  "ja",
  "ko",
  "ru",
  "de",
  "fr",
  "es",
  "pt",
] as const;

export type DynamicUiLocale = (typeof DYNAMIC_UI_LOCALES)[number];

export type UiLocale = FixedUiLocale | DynamicUiLocale;

export const UI_LOCALE_LABELS: Record<UiLocale, string> = {
  "zh-CN": "中文",
  "en-US": "English",
  ja: "日本語",
  ko: "한국어",
  ru: "Русский",
  de: "Deutsch",
  fr: "Français",
  es: "Español",
  pt: "Português",
};

export const ALL_UI_LOCALES: UiLocale[] = [
  ...FIXED_UI_LOCALES,
  ...DYNAMIC_UI_LOCALES,
];

export function isFixedUiLocale(locale: string): locale is FixedUiLocale {
  return (FIXED_UI_LOCALES as readonly string[]).includes(locale);
}

export function isDynamicUiLocale(locale: string): locale is DynamicUiLocale {
  return (DYNAMIC_UI_LOCALES as readonly string[]).includes(locale);
}

export function isUiLocale(locale: string): locale is UiLocale {
  return isFixedUiLocale(locale) || isDynamicUiLocale(locale);
}

/** Map translator target language codes to UI locale ids. */
export function mapTargetLangToUiLocale(targetLanguage: string): UiLocale | null {
  const map: Record<string, UiLocale> = {
    "zh-CN": "zh-CN",
    zh: "zh-CN",
    "en-US": "en-US",
    en: "en-US",
    ja: "ja",
    ko: "ko",
    ru: "ru",
    de: "de",
    fr: "fr",
    es: "es",
    pt: "pt",
  };
  return map[targetLanguage] ?? null;
}
