import {
  dynamicLocales,
  fixedLocales,
  isFixedLocale,
  localeLabels,
  type AppLocale,
  type DynamicLocale,
  type FixedLocale,
} from "./config";

/** Built-in packs shipped as JSON under messages/. */
export const FIXED_UI_LOCALES = fixedLocales;
export type FixedUiLocale = FixedLocale;

/** Extended UI languages generated by Locale Pack Agent (BYOK). */
export const DYNAMIC_UI_LOCALES = dynamicLocales;
export type DynamicUiLocale = DynamicLocale;

export type UiLocale = AppLocale;

export const UI_LOCALE_LABELS: Record<UiLocale, string> = localeLabels;

export const ALL_UI_LOCALES: UiLocale[] = [
  ...FIXED_UI_LOCALES,
  ...DYNAMIC_UI_LOCALES,
];

export function isFixedUiLocale(locale: string): locale is FixedUiLocale {
  return isFixedLocale(locale);
}

export function isDynamicUiLocale(locale: string): locale is DynamicUiLocale {
  return (DYNAMIC_UI_LOCALES as readonly string[]).includes(locale);
}

export function isUiLocale(locale: string): locale is UiLocale {
  return isFixedUiLocale(locale) || isDynamicUiLocale(locale);
}

/** Map translator target language codes to UI locale ids. */
export function mapTargetLangToUiLocale(targetLanguage: string): UiLocale | null {
  const map: Record<string, UiLocale> = {
    "zh-CN": "zh-CN",
    zh: "zh-CN",
    "en-US": "en-US",
    en: "en-US",
    ja: "ja",
    ko: "ko",
    ru: "ru",
    de: "de",
    fr: "fr",
    es: "es",
    pt: "pt",
  };
  return map[targetLanguage] ?? null;
}
